name: "Ensure the broken anchors are fixed before merging"

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm@latest

      - name: Install dependencies
        run: pnpm install

      - name: Verify broken anchors are fixed
        run: |
          set -e
          output=$(pnpm build 2>&1)

          echo "$output" | awk '
            /Broken anchor on source page path/ { printing=1 }
            printing { print }
            /^$/ && printing { printing=0 }
          ' > broken.log

          grep -vP "/dev/\d+\.\d+\.\d+/" broken.log > broken_anchors.log
          if [ -s broken_anchors.log ]; then
            echo "Broken anchors found"
            cat broken_anchors.log
            exit 1
          fi